# Generated by Django 3.0.6 on 2020-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Company_name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=25)),
                ('Contact_no', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Contactus',
            },
        ),
    ]
