# Generated by Django 3.0.6 on 2020-06-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand_name', models.CharField(max_length=10)),
                ('Brand_img', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=25)),
                ('Item_img', models.ImageField(upload_to='media')),
                ('Range', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=40)),
                ('Company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
