# Generated by Django 3.0.6 on 2020-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brands_company_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
