# Generated by Django 3.0.6 on 2020-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200615_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='Brand_name',
            field=models.CharField(max_length=30),
        ),
    ]
