# Generated by Django 3.0.6 on 2020-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200618_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_img',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
