# Generated by Django 3.0.6 on 2020-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_company_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Company_name',
            new_name='Company_id',
        ),
    ]
